
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// Prisma 6 hands env loading to this config (it no longer auto-reads .env*).
// `import "dotenv/config"` loads only `.env`, but DIRECT_URL (and the real
// DATABASE_URL) live in `.env.local`, so load that first — dotenv does not
// override already-set vars, so `.env.local` takes priority over `.env`.
import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });
loadEnv({ path: ".env" });
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
});
