import { Play, ImageIcon, Clapperboard } from 'lucide-react';

/* Card art is generated by scripts/generate-showcase-images.ts and written to
   public/showcase — stills from gpt-image-1, clips from Veo. Re-run that script
   to refresh the art; the prompts here are the captions shown on the card, and
   the real generation prompts live in the script alongside them.

   Each card is tagged with the product surface it demonstrates rather than a
   generic "AI image / AI video" label, so the grid doubles as a tour of what
   the studio actually does: generate stills, cut viral ad shorts, shoot
   original-series footage, and turn a product into a UGC testimonial.

   `clip` is set only on items whose .mp4 has actually been rendered. Without it
   a video card shows its still under the play badge, so the section degrades to
   exactly what it was before rather than to a broken <video>.

   `portrait` marks the cards whose asset is 9:16, because the pillar they
   demonstrate is a vertical format. The card frame stays 4:3 so the grid keeps
   its rhythm; the vertical asset is letterboxed inside it against a blurred
   copy of itself, which shows the real delivery shape instead of centre-
   cropping it away. */
const SHOWCASE_ITEMS: {
  kind: 'image' | 'video';
  /** Which product surface this card is showing off — rendered as the eyebrow. */
  pillar: string;
  prompt: string;
  duration?: string;
  art: string;
  clip?: string;
  /** Asset is 9:16 rather than 16:9 — see scripts/generate-showcase-images.ts. */
  portrait?: boolean;
}[] = [
  {
    kind: 'video',
    pillar: 'Viral shorts',
    prompt: 'Product launch teaser — smoothie pour in slow motion, studio lighting',
    duration: '0:08',
    art: '/showcase/smoothie.webp',
    clip: '/showcase/smoothie.mp4',
    portrait: true,
  },
  {
    kind: 'image',
    pillar: 'Creator studio',
    prompt: 'Neon jellyfish drifting through a deep indigo ocean, cinematic light',
    art: '/showcase/jellyfish.webp',
  },
  {
    kind: 'video',
    pillar: 'Original series',
    prompt: 'Opening shot of an original series — neon rooftop, anamorphic',
    duration: '0:08',
    art: '/showcase/cinematic.webp',
    clip: '/showcase/cinematic.mp4',
  },
  {
    kind: 'video',
    pillar: 'UGC marketing',
    prompt: 'UGC ad in one click — creator testimonial, shot-on-phone look',
    duration: '0:08',
    art: '/showcase/ugc-creator.webp',
    clip: '/showcase/ugc-creator.mp4',
    portrait: true,
  },
  {
    kind: 'image',
    pillar: 'Marketing studio',
    prompt: 'Minimal product shot — matcha jar on emerald silk, soft shadows',
    art: '/showcase/matcha.webp',
  },
  {
    kind: 'video',
    pillar: 'Creator studio',
    prompt: 'Animated brand story — logo morphing through liquid color',
    duration: '0:08',
    art: '/showcase/brandstory.webp',
    clip: '/showcase/brandstory.mp4',
  },
];

export default function ShowcaseGallery() {
  return (
    <section className="relative max-w-6xl mx-auto px-4 md:px-8 py-20 border-t border-border">
      <div className="text-center mb-12">
        <h2 className="text-3xl md:text-5xl font-bold tracking-tight text-foreground mb-4">
          Images. Video. <span className="text-gradient">Made from a sentence.</span>
        </h2>
        <p className="text-muted-foreground max-w-2xl mx-auto text-lg">
          One studio for stills, ad shorts, original-series footage, and UGC testimonials —
          no design tools, no stock-photo subscriptions, no video editor.
        </p>
      </div>

      <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">
        {SHOWCASE_ITEMS.map((item) => (
          <figure
            key={item.art}
            className="group relative rounded-2xl overflow-hidden border border-border shadow-lg hover:shadow-2xl hover:-translate-y-1 transition-all"
          >
            <div className="relative aspect-[4/3] w-full overflow-hidden bg-black flex items-center justify-center">
              {/* A 9:16 asset in a 4:3 frame would lose the top and bottom of the
                  shot to object-cover. Contain it instead, and fill the gutters
                  with a blurred copy so the letterboxing reads as framing. */}
              {item.portrait && (
                <img
                  src={item.art}
                  alt=""
                  aria-hidden="true"
                  className="absolute inset-0 h-full w-full object-cover scale-125 blur-2xl opacity-50"
                />
              )}

              {item.clip ? (
                <video
                  src={item.clip}
                  poster={item.art}
                  autoPlay
                  muted
                  loop
                  playsInline
                  preload="metadata"
                  aria-label={item.prompt}
                  className={
                    item.portrait
                      ? 'relative max-h-full max-w-full object-contain group-hover:scale-105 transition-transform duration-500'
                      : 'h-full w-full object-cover group-hover:scale-105 transition-transform duration-500'
                  }
                />
              ) : (
                <img
                  src={item.art}
                  alt={item.prompt}
                  className={
                    item.portrait
                      ? 'relative max-h-full max-w-full object-contain group-hover:scale-105 transition-transform duration-500'
                      : 'h-full w-full object-cover group-hover:scale-105 transition-transform duration-500'
                  }
                />
              )}
            </div>

            {item.kind === 'video' && (
              <>
                {/* The play badge is a still-frame affordance. Once a clip is
                    playing it would only cover the thing it advertises. */}
                {!item.clip && (
                  <span className="absolute inset-0 flex items-center justify-center">
                    <span className="w-14 h-14 rounded-full bg-white/20 backdrop-blur-sm border border-white/40 flex items-center justify-center group-hover:scale-110 transition-transform">
                      <Play className="w-6 h-6 text-white fill-white ml-0.5" />
                    </span>
                  </span>
                )}
                <span className="absolute top-3 right-3 px-2 py-0.5 rounded-md bg-black/50 backdrop-blur-sm text-xs font-mono text-white">
                  {item.duration}
                </span>
              </>
            )}

            <figcaption className="absolute inset-x-0 bottom-0 p-4 bg-gradient-to-t from-black/80 via-black/40 to-transparent">
              <span className="flex items-center gap-1.5 text-[11px] font-semibold uppercase tracking-wider text-emerald-300 mb-1">
                {item.kind === 'video' ? (
                  <Clapperboard className="w-3.5 h-3.5" />
                ) : (
                  <ImageIcon className="w-3.5 h-3.5" />
                )}
                {item.pillar}
              </span>
              <span className="block text-sm text-white/90 font-mono leading-snug">
                “{item.prompt}”
              </span>
            </figcaption>
          </figure>
        ))}
      </div>
    </section>
  );
}
